name: floating
description: Picture in Picture mode management for Flutter. Available only for Android.
version: 6.0.0
homepage: https://github.com/wrbl606/floating
screenshots:
  - description: 'This screenshot shows the transformation from a full-screen application to a movable picture-in-picture form.'
    path: assets/cover.png
topics:
  - widgets
  - picture-in-picture
  - android
  - flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        package: eu.wroblewscy.marcin.floating.floating
        pluginClass: FloatingPlugin
